name: Example App

on:
  push:
    branches: [ main, example-app ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_DB: test
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pgsql, pdo_pgsql

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Install dependencies
        run: composer install --working-dir=docs/example --prefer-dist --no-progress

      - name: Create test_test database
        env:
          PGPASSWORD: ""
        run: createdb -h localhost -p 5432 -U test test_test

      - name: Run tests
        working-directory: docs/example
        run: ./vendor/bin/phpunit
